export const FETCH_CONSUMER = 'FETCH_CONSUMER';
export const FETCH_CONSUMER_ID = 'FETCH_CONSUMER_ID';
export const FETCT_NEW_CONSUMER = 'FETCT_NEW_CONSUMER';
export const FETCH_DELETE_CONSUMER = 'FETCH_DELETE_CONSUMER';
export const FETCH_UPDATE_CONSUMER = 'FETCH_UPDATE_CONSUMER';
export const FETCH_COUNT = 'FETCH_COUNT';
export const FETCH_SEARCH = 'FETCH_SEARCH';